### ISSUE TITLE
this is an empty source

### ISSUE THREAD

**Issue by MohebYasser** [danimahardhika/wallpaperboard-sample#1]
hi sir
can you pleas till me how to bulid complete app with this source 
this source dosint have any thing inside it only 2 activitys !!!
ware is splash photos and app colors and strings and style !!!

thanks and have a good day

**Comment by danimahardhika** [comment]
@MohebYasser This is the wiki site https://github.com/danimahardhika/wallpaperboard/wiki and **NO** this is not empty source, read wiki site first.
